export { default as Home } from './home/Home'
export { default as About } from './about/About'
export { default as CTA } from './cta/CTA'
export { default as Contact } from './contact/Contact'
export { default as Navbar } from './navbar/Navbar'
export { default as Profile } from './profile/Profile'